- name: Install Aleph.im compute resource nodes
  hosts: compute_hosts
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Docker
      become: true
      apt:
        name: docker.io
        state: present

    - name: Launch the VM-Connector
      docker_container:
        name: vm-connector
        image: alephim/vm-connector:alpha
        restart_policy: always
        ports:
          - "127.0.0.1:4021:4021/tcp"
        state: started

    - name: Install the VM-Supervisor
      apt:
        deb: https://github.com/aleph-im/aleph-vm/releases/download/{{ node_version }}/aleph-vm.ubuntu-22.04.deb

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      reboot:
      when: reboot_required.stat.exists

    - name: Set the domain name in supervisor.env
      lineinfile:
        path: /etc/aleph-vm/supervisor.env
        regexp: '^ALEPH_VM_DOMAIN_NAME='
        line: ALEPH_VM_DOMAIN_NAME={{ domain }}
        create: true
      register: update_env

    - name: Restart the VM-Supervisor service
      service:
        name: aleph-vm-supervisor
        state: restarted
      when: update_env.changed

    - name: Install Caddy
      import_tasks:
        file: tasks/install_caddy.yaml

    - name: Set Caddyfile
      copy:
        dest: /etc/caddy/Caddyfile
        content: |
          {
              https_port 443
              on_demand_tls {
                  interval 60s
                  burst    5
              }
          }
          {{ domain }}:443 {
              reverse_proxy http://127.0.0.1:4020 {
                  # Forward Host header to the backend
                  header_up Host {host}
              }
          }
      register: caddyfile

    - name: Restart Caddy service
      service:
        name: caddy
        enabled: yes
        state: restarted
      when: caddyfile.changed
