- name: Aleph.im compute resource nodes
  hosts: compute_hosts
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Docker
      become: true
      apt:
        name: docker.io
        state: present

    - name: Launch the VM-Connector
      docker_container:
        name: vm-connector
        image: alephim/vm-connector:alpha
        restart_policy: always
        ports:
          - "127.0.0.1:4021:4021/tcp"
        state: started

    - name: Install the VM-Supervisor
      apt:
        deb: https://github.com/aleph-im/aleph-vm/releases/download/0.3.1/aleph-vm.ubuntu-22.04.deb

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      reboot:
      when: reboot_required.stat.exists
